/* Supabase joins are dynamic until generated database types are added. */
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Image from "next/image";import Link from "next/link";import {useMemo,useState} from "react";import {createClient} from "@/lib/supabase/client";import {PrimeArrowIcon} from "@/components/prime-icons";
type Item=Record<string,any>; const money=(c:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);const dt=(v:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(v));
export default function AdminDashboard({adminName,appointments:initial,services:initialServices,professionals:initialPros,plans,clients,memberships}:any){const [tab,setTab]=useState("agenda");const [appointments,setAppointments]=useState<Item[]>(initial);const [services,setServices]=useState<Item[]>(initialServices);const [pros,setPros]=useState<Item[]>(initialPros);const [feedback,setFeedback]=useState("");const supabase=useMemo(()=>createClient(),[]);const today=new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"});const todays=appointments.filter(a=>new Date(a.starts_at).toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"})===today);const expected=todays.filter(a=>!["cancelled","no_show"].includes(a.status)&&a.payment_mode==="at_shop").reduce((n,a)=>n+(a.services?.price_cents||0),0);
  async function status(id:string,next:string){if(next==="no_show"&&!confirm("Marcar como não comparecimento? O cliente ficará bloqueado para novos agendamentos por 24 horas."))return;const fn=next==="no_show"?"mark_no_show":"admin_set_appointment_status";const args=next==="no_show"?{p_appointment_id:id}:{p_appointment_id:id,p_status:next};const {error}=await supabase.rpc(fn,args);if(error)setFeedback(error.message);else{setAppointments(list=>list.map(a=>a.id===id?{...a,status:next}:a));setFeedback("Agenda atualizada.");}}
  async function saveService(service:Item,form:HTMLFormElement){const data=new FormData(form);const patch={price_cents:Math.round(Number(data.get("price"))*100),duration_minutes:Number(data.get("duration")),active:data.get("active")==="on"};const {error}=await supabase.from("services").update(patch).eq("id",service.id);if(error)setFeedback(error.message);else{setServices(list=>list.map(s=>s.id===service.id?{...s,...patch}:s));setFeedback(`${service.name} atualizado.`);}}
  async function togglePro(pro:Item){const {error}=await supabase.from("professionals").update({active:!pro.active}).eq("id",pro.id);if(error)setFeedback(error.message);else setPros(list=>list.map(p=>p.id===pro.id?{...p,active:!p.active}:p));}
  async function assignPlan(clientId:string,planId:string){if(!planId)return;const current=memberships.find((m:Item)=>m.client_id===clientId&&m.active);if(current)await supabase.from("memberships").update({active:false,ends_on:new Date().toISOString().slice(0,10)}).eq("id",current.id);const {error}=await supabase.from("memberships").insert({client_id:clientId,plan_id:planId,starts_on:new Date().toISOString().slice(0,10),active:true});setFeedback(error?error.message:"Plano vinculado. Recarregue para atualizar a listagem.");}
  return <main className="portal-shell admin-portal"><aside className="portal-side"><Link href="/" className="prime-brand"><Image src="/logo-neemias-prime.png" alt="Neemias Prime" width={48} height={48}/><span>NEEMIAS <b>PRIME</b></span></Link><nav><button className={tab==="agenda"?"active":""} onClick={()=>setTab("agenda")}>▦ Agenda</button><button className={tab==="clientes"?"active":""} onClick={()=>setTab("clientes")}>♙ Clientes e planos</button><button className={tab==="servicos"?"active":""} onClick={()=>setTab("servicos")}>◇ Serviços</button><button className={tab==="equipe"?"active":""} onClick={()=>setTab("equipe")}>✂ Equipe</button><Link href="/cliente"><PrimeArrowIcon /> Área do cliente</Link></nav><Link className="logout" href="/sair">Sair da conta</Link></aside><section className="portal-main"><header className="portal-top"><div><small>ADMINISTRAÇÃO</small><strong>{adminName}</strong></div><span className="client-avatar">ADM</span></header><div className="portal-content"><section className="admin-heading"><div><p className="metal-kicker">CENTRAL DE OPERAÇÃO</p><h1>{tab==="agenda"?"Agenda da barbearia":tab==="clientes"?"Clientes e assinaturas":tab==="servicos"?"Catálogo de serviços":"Equipe profissional"}</h1></div><span>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"full"}).format(new Date())}</span></section>{feedback&&<div className="inline-feedback">{feedback}<button onClick={()=>setFeedback("")}>×</button></div>}
  {tab==="agenda"&&<><section className="admin-metrics"><article><small>ATENDIMENTOS HOJE</small><strong>{todays.length}</strong></article><article><small>RECEITA PREVISTA</small><strong>{money(expected)}</strong></article><article><small>COBERTOS POR PLANO</small><strong>{todays.filter(a=>a.payment_mode==="membership").length}</strong></article><article><small>CLIENTES CADASTRADOS</small><strong>{clients.length}</strong></article></section><section className="admin-list"><div className="admin-list-head"><span>DATA / HORA</span><span>CLIENTE E SERVIÇO</span><span>PROFISSIONAL</span><span>SITUAÇÃO</span><span>AÇÕES</span></div>{appointments.map(a=><article key={a.id}><time>{dt(a.starts_at)}</time><div><strong>{a.profiles?.full_name}</strong><small>{a.services?.name} · {a.payment_mode==="membership"?"Plano":money(a.services?.price_cents||0)}</small></div><span>{a.professionals?.name}</span><i className={`appointment-status ${a.status}`}>{({scheduled:"Agendado",confirmed:"Confirmado",completed:"Concluído",cancelled:"Cancelado",no_show:"Não compareceu"} as Item)[a.status]}</i><div className="row-actions">{["scheduled","confirmed"].includes(a.status)&&<><button onClick={()=>status(a.id,"completed")}>Concluir</button><button className="danger" onClick={()=>status(a.id,"no_show")}>Não compareceu</button><button onClick={()=>status(a.id,"cancelled")}>Cancelar</button></>}</div></article>)}</section></>}
  {tab==="clientes"&&<section className="client-admin-grid">{clients.map((c:Item)=>{const member=memberships.find((m:Item)=>m.client_id===c.id&&m.active);return <article key={c.id}><div className="client-avatar">{(c.full_name||"CL").split(" ").slice(0,2).map((x:string)=>x[0]).join("")}</div><div><strong>{c.full_name||"Sem nome"}</strong><small>{c.phone||"Telefone não informado"}</small>{c.booking_blocked_until&&new Date(c.booking_blocked_until)>new Date()&&<em>Bloqueado até {dt(c.booking_blocked_until)}</em>}</div><label>Plano atual<select defaultValue={member?.plan_id||""} onChange={e=>assignPlan(c.id,e.target.value)}><option value="">Sem plano</option>{plans.map((p:Item)=><option key={p.id} value={p.id}>{p.name} · {money(p.price_cents)}</option>)}</select></label></article>})}</section>}
  {tab==="servicos"&&<section className="catalog-admin">{services.map((s:Item)=><form key={s.id} onSubmit={e=>{e.preventDefault();saveService(s,e.currentTarget)}}><div><strong>{s.name}</strong><small>{s.active?"Disponível para agendamento":"Oculto dos clientes"}</small></div><label>Preço (R$)<input name="price" type="number" min="0" step="0.01" defaultValue={(s.price_cents/100).toFixed(2)}/></label><label>Duração<input name="duration" type="number" min="5" step="5" defaultValue={s.duration_minutes}/></label><label className="check"><input name="active" type="checkbox" defaultChecked={s.active}/> Ativo</label><button>Salvar</button></form>)}</section>}
  {tab==="equipe"&&<section className="team-admin">{pros.map((p:Item)=><article key={p.id}><div className="client-avatar">{p.name.split(" ").map((x:string)=>x[0]).slice(0,2).join("")}</div><div><strong>{p.name}</strong><small>{p.active?"Recebendo agendamentos":"Agenda desativada"}</small></div><button className={p.active?"danger":""} onClick={()=>togglePro(p)}>{p.active?"Desativar agenda":"Ativar agenda"}</button></article>)}</section>}
  </div></section></main>;
}
