"use client";

import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ClientMobileNav, ClientSection, ClientSidebar, ClientTopbar } from "@/components/client-navigation";
import styles from "./appointments-dashboard.module.css";

type Professional={id:string;name:string};
type Appointment={id:string;service_id:string;professional_id:string;starts_at:string;ends_at:string;status:string;payment_mode:string;services:{name:string;price_cents:number;duration_minutes:number}|null;professionals:{name:string}|null};
type Props={profile:{full_name:string;role:string;booking_blocked_until:string|null}|null;appointments:Appointment[];professionals:Professional[];onNavigate?:(section:ClientSection)=>void};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value/100);
const clock=(value:string)=>new Date(value).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"});
const statusLabel:Record<string,string>={scheduled:"Agendado",confirmed:"Confirmado",completed:"Concluído",cancelled:"Cancelado",no_show:"Não compareceu"};
function dateValue(date:Date){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const get=(type:string)=>parts.find(part=>part.type===type)?.value||"";return `${get("year")}-${get("month")}-${get("day")}`}
function sevenDays(){const base=new Date();return Array.from({length:7},(_,i)=>{const date=new Date(base);date.setDate(base.getDate()+i);const key=new Intl.DateTimeFormat("en-US",{weekday:"short",timeZone:"America/Sao_Paulo"}).format(date);return{value:dateValue(date),week:i===0?"Hoje":new Intl.DateTimeFormat("pt-BR",{weekday:"short",timeZone:"America/Sao_Paulo"}).format(date).replace(".",""),day:new Intl.DateTimeFormat("pt-BR",{day:"2-digit",timeZone:"America/Sao_Paulo"}).format(date),month:new Intl.DateTimeFormat("pt-BR",{month:"short",timeZone:"America/Sao_Paulo"}).format(date).replace(".",""),closed:key==="Sun"||key==="Mon"}})}

export default function AppointmentsDashboard({profile,appointments:initial,professionals,onNavigate}:Props){
  const [appointments,setAppointments]=useState(initial);const [tab,setTab]=useState<"next"|"history">("next");const [editing,setEditing]=useState<Appointment|null>(null);const [professional,setProfessional]=useState("");const days=useMemo(()=>sevenDays(),[]);const [date,setDate]=useState(days.find(d=>!d.closed)?.value||"");const [slots,setSlots]=useState<string[]>([]);const [slot,setSlot]=useState("");const [loading,setLoading]=useState(false);const [feedback,setFeedback]=useState("");
  const now=new Date();const upcoming=appointments.filter(item=>["scheduled","confirmed"].includes(item.status)&&new Date(item.starts_at)>now).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));const history=appointments.filter(item=>!upcoming.some(next=>next.id===item.id));const shown=tab==="next"?upcoming:history;
  useEffect(()=>{if(!editing||!professional||!date)return;let active=true;(async()=>{setLoading(true);const {data,error}=await createClient().rpc("available_slots",{p_professional_id:professional,p_service_id:editing.service_id,p_date:date});if(active){setSlots(error?[]:(data||[]).map((x:{starts_at:string})=>x.starts_at).filter((value:string)=>value!==editing.starts_at));setSlot("");setLoading(false);}})();return()=>{active=false}},[editing,professional,date]);
  function openReschedule(item:Appointment){setEditing(item);setProfessional(item.professional_id);setDate(days.find(day=>!day.closed)?.value||"");setFeedback("");}
  async function reschedule(){if(!editing||!slot)return;setLoading(true);const {error}=await createClient().rpc("reschedule_my_appointment",{p_appointment_id:editing.id,p_professional_id:professional,p_starts_at:slot});if(error){setFeedback(error.message);setLoading(false);return;}const duration=Math.max(30,editing.services?.duration_minutes||30);setAppointments(list=>list.map(item=>item.id===editing.id?{...item,professional_id:professional,starts_at:slot,ends_at:new Date(new Date(slot).getTime()+duration*60000).toISOString(),professionals:{name:professionals.find(p=>p.id===professional)?.name||"Profissional"}}:item));setEditing(null);setLoading(false);setFeedback("Horário reagendado com sucesso.");}
  async function cancel(item:Appointment){if(!confirm("Deseja cancelar este horário?"))return;const {error}=await createClient().rpc("cancel_my_appointment",{p_appointment_id:item.id});if(error)setFeedback(error.message);else setAppointments(list=>list.map(value=>value.id===item.id?{...value,status:"cancelled"}:value));}
  function goTo(section:ClientSection){if(onNavigate){onNavigate(section);return;}const hash:Record<ClientSection,string>={home:"inicio",booking:"agendar",appointments:"meus-agendamentos",plans:"plano",profile:"perfil"};window.location.assign(`/cliente#${hash[section]}`);}
  return <main className={`${styles.root} portal-shell`}>
    <ClientSidebar active="appointments" profileName={profile?.full_name||"Cliente Prime"} isAdmin={profile?.role==="admin"} onNavigate={goTo}/>
    <section className="portal-main appointments-main"><ClientTopbar active="appointments" profileName={profile?.full_name||"Cliente Prime"} isAdmin={profile?.role==="admin"} onNavigate={goTo}/><div className="appointments-content">
      <section className="appointments-hero"><div><p>MINHA AGENDA PRIME</p><h1>Seus horários,<br/><em>do seu jeito.</em></h1><span>Veja detalhes, valores e reagende sem precisar enviar mensagem.</span></div><button type="button" className="new-appointment" onClick={()=>goTo("booking")}>NOVO AGENDAMENTO <b>＋</b></button><i>NP</i></section>
      {feedback&&<div className="appointments-feedback">{feedback}<button onClick={()=>setFeedback("")}>×</button></div>}
      <div className="appointments-tabs"><button className={tab==="next"?"active":""} onClick={()=>setTab("next")}>Próximos <span>{upcoming.length}</span></button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Histórico <span>{history.length}</span></button></div>
      <section className="appointment-list">{shown.length?shown.map((item,index)=><article className={tab==="next"&&index===0?"featured":""} key={item.id}><div className="appointment-date"><small>{new Intl.DateTimeFormat("pt-BR",{weekday:"short",timeZone:"America/Sao_Paulo"}).format(new Date(item.starts_at)).replace(".","")}</small><strong>{new Intl.DateTimeFormat("pt-BR",{day:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(item.starts_at))}</strong><span>{new Intl.DateTimeFormat("pt-BR",{month:"short",timeZone:"America/Sao_Paulo"}).format(new Date(item.starts_at)).replace(".","")}</span></div><div className="appointment-data"><div className="appointment-title"><span>{item.services?.name?.includes("Barba")?"B":"✦"}</span><div><small>{index===0&&tab==="next"?"SEU PRÓXIMO HORÁRIO":"ATENDIMENTO"}</small><h2>{item.services?.name}</h2></div></div><div className="appointment-meta"><span><small>HORÁRIO</small><b>{clock(item.starts_at)}</b></span><span><small>PROFISSIONAL</small><b>{item.professionals?.name}</b></span><span><small>VALOR</small><b>{item.payment_mode==="membership"?"Coberto pelo plano":money(item.services?.price_cents||0)}</b></span></div></div><div className="appointment-state"><span className={item.status}>{statusLabel[item.status]}</span>{["scheduled","confirmed"].includes(item.status)&&<div><button className="reschedule" onClick={()=>openReschedule(item)}>Reagendar</button><button onClick={()=>cancel(item)}>Cancelar</button></div>}</div></article>):<div className="appointments-empty"><span>◷</span><h2>{tab==="next"?"Nenhum horário marcado":"Seu histórico está vazio"}</h2><p>{tab==="next"?"Escolha um serviço e encontre o melhor horário para você.":"Seus atendimentos aparecerão aqui."}</p>{tab==="next"&&<button type="button" onClick={()=>goTo("booking")}>AGENDAR AGORA →</button>}</div>}</section>
    </div></section>
    <ClientMobileNav active="appointments" onNavigate={goTo}/>
    {editing&&<div className="reschedule-backdrop"><section className="reschedule-modal"><button className="modal-close" onClick={()=>setEditing(null)}>×</button><p>REAGENDAR ATENDIMENTO</p><h2>Escolha o novo horário</h2><div className="current-booking"><span>DE</span><b>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(editing.starts_at))}</b><small>{editing.services?.name}</small></div><label>Profissional<div className="modal-professionals">{professionals.map(item=><button className={professional===item.id?"selected":""} onClick={()=>setProfessional(item.id)} key={item.id}>{item.name}</button>)}</div></label><label>Novo dia<div className="modal-days">{days.map(item=><button disabled={item.closed} className={date===item.value?"selected":""} onClick={()=>setDate(item.value)} key={item.value}><small>{item.week}</small><b>{item.day}</b></button>)}</div></label><label>Novo horário<div className="modal-slots">{loading?<small>Consultando...</small>:slots.length?slots.map(item=><button className={slot===item?"selected":""} onClick={()=>setSlot(item)} key={item}>{clock(item)}</button>):<small>Nenhum horário disponível neste dia.</small>}</div></label><button className="confirm-reschedule" disabled={!slot||loading} onClick={reschedule}>CONFIRMAR NOVO HORÁRIO <span>→</span></button></section></div>}
  </main>;
}
